In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("NYC_Jobs.csv")
data.head()

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC HOUSING AUTHORITY,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0

In [4]:
data.isnull().sum()

Job ID                 0
Civil Service Title    0
Agency                 0
Posting Type           0
Job Category           3
Salary Range From      0
Salary Range To        0
dtype: int64

In [8]:
data[data['Job Category'].isnull()]

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,NaN,82884.0,116391.0
2205,87990,CONTRACT REVIEWER (OFFICE OF L,DEPARTMENT OF BUSINESS SERV.,Internal,NaN,42405.0,65485.0
2945,97899,ADMINISTRATIVE BUSINESS PROMOT,DEPARTMENT OF BUSINESS SERV.,Internal,NaN,60740.0,162014.0

In [10]:
data = data.fillna("Legal Affairs")
data.isnull().sum()

Job ID                 0
Civil Service Title    0
Agency                 0
Posting Type           0
Job Category           0
Salary Range From      0
Salary Range To        0
dtype: int64

In [13]:
data.replace('NYC HOUSING AUTHORITY', 'NYC AUTHORITY FOR HOUSING', inplace = True)
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,External,Health,84252.0,84252.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,External,Legal Affairs,82884.0,116391.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,External,Legal Affairs,105000.0,125000.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,External,Information Technology & Telecommunications,87203.0,131623.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,External,Constituent Services & Community Programs,58449.0,67216.0
...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,External,Legal Affairs,62397.0,71757.0

In [17]:
data.loc[data['Posting Type']=='External', "Posting Type"] = 1
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Posting TYpe
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health,84252.0,84252.0,1.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,1.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,1.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,1.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,1.0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,Internal,"Technology, Data & Innovation",85371.0,119883.0,NaN
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,Internal,"Engineering, Architecture, & Planning",74650.0,85847.0,NaN
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,Internal,"Technology, Data & Innovation",100000.0,115000.0,NaN
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,Internal,"Finance, Accounting, & Procurement",42288.0,59400.0,NaN
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1.0

In [20]:
data.loc[data['Posting Type']=='Internal', 'Posting Type']=2
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Posting TYpe
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health,84252.0,84252.0,1.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,1.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,1.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,1.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,1.0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,NaN
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,NaN
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,NaN
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,NaN
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1.0

In [37]:

#data.at[data['Job Category'] == "Health", "Job Category"] = "Health Dept."


data.loc[data['Job Category'] == "Health", "Job Category"] = "Health Dept."

In [36]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Posting TYpe
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health,84252.0,84252.0,1.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,1.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,1.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,1.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,1.0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,NaN
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,NaN
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,NaN
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,NaN
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1.0

In [38]:
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Posting TYpe
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health Dept.,84252.0,84252.0,1.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,1.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,1.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,Information Technology & Telecommunications,87203.0,131623.0,1.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,1.0
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,NaN
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,NaN
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,NaN
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,NaN
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,1.0

In [39]:
data.loc[3, 'Job Category'] = "ITT"
data.head()

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Posting TYpe
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health Dept.,84252.0,84252.0,1.0
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,1.0
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,1.0
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,ITT,87203.0,131623.0,1.0
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,1.0

In [40]:
data.columns

Index(['Job ID', 'Civil Service Title', 'Agency', 'Posting Type',
       'Job Category', 'Salary Range From', 'Salary Range To', 'Posting TYpe'],
      dtype='object')

In [44]:
data = data.drop('Posting TYpe', axis = 1)

In [45]:
data.columns

Index(['Job ID', 'Civil Service Title', 'Agency', 'Posting Type',
       'Job Category', 'Salary Range From', 'Salary Range To'],
      dtype='object')

In [48]:
data['Financial_Boolean'] = np.where(data['Agency'] == 'FINANCIAL INFO SVCS AGENCY', True, False)
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Financial_Boolean
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health Dept.,84252.0,84252.0,False
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,False
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,False
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,ITT,87203.0,131623.0,False
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,False
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,False
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,False
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,True
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,False
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,False

In [51]:
data[data['Financial_Boolean'] == False]

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Financial_Boolean
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health Dept.,84252.0,84252.0,False
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,False
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,False
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,ITT,87203.0,131623.0,False
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,False
...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,False
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,False
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,False
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,False
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,False

In [62]:
data['Agency'].mask(data['Civil Service Title']=="PUBLIC HEALTH NURSE", 0)

0                                    0
1         NYC EMPLOYEES RETIREMENT SYS
2            NYC AUTHORITY FOR HOUSING
3         NYC EMPLOYEES RETIREMENT SYS
4              HUMAN RIGHTS COMMISSION
                     ...
3768      NYC EMPLOYEES RETIREMENT SYS
3769    HOUSING PRESERVATION & DVLPMNT
3770        FINANCIAL INFO SVCS AGENCY
3771     DEPT OF HEALTH/MENTAL HYGIENE
3772           HUMAN RIGHTS COMMISSION
Name: Agency, Length: 3773, dtype: object

In [65]:
data['salary lower limit ranges'] = pd.cut(data["Salary Range From"], 3)
data

,Job ID,Civil Service Title,Agency,Posting Type,Job Category,Salary Range From,Salary Range To,Financial_Boolean,salary lower limit ranges
0,424339,PUBLIC HEALTH NURSE,DEPT OF HEALTH/MENTAL HYGIENE,1,Health Dept.,84252.0,84252.0,False,"(83333.333, 166666.667]"
1,379094,CERT IT DEVELOPER (APP),NYC EMPLOYEES RETIREMENT SYS,1,Legal Affairs,82884.0,116391.0,False,"(-250.0, 83333.333]"
2,520417,EXECUTIVE AGENCY COUNSEL,NYC AUTHORITY FOR HOUSING,1,Legal Affairs,105000.0,125000.0,False,"(83333.333, 166666.667]"
3,233549,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,1,ITT,87203.0,131623.0,False,"(83333.333, 166666.667]"
4,510256,ASSOCIATE HUMAN RIGHTS SPECIAL,HUMAN RIGHTS COMMISSION,1,Constituent Services & Community Programs,58449.0,67216.0,False,"(-250.0, 83333.333]"
...,...,...,...,...,...,...,...,...,...
3768,457839,CERTIFIED IT ADMINISTRATOR (LA,NYC EMPLOYEES RETIREMENT SYS,2,"Technology, Data & Innovation",85371.0,119883.0,False,"(83333.333, 166666.667]"
3769,527141,ASSOCIATE HOUSING DEVELOPMENT,HOUSING PRESERVATION & DVLPMNT,2,"Engineering, Architecture, & Planning",74650.0,85847.0,False,"(-250.0, 83333.333]"
3770,509443,SENIOR IT ARCHITECT,FINANCIAL INFO SVCS AGENCY,2,"Technology, Data & Innovation",100000.0,115000.0,False,"(83333.333, 166666.667]"
3771,352367,ECONOMIST,DEPT OF HEALTH/MENTAL HYGIENE,2,"Finance, Accounting, & Procurement",42288.0,59400.0,False,"(-250.0, 83333.333]"
3772,478739,AGENCY ATTORNEY INTERNE,HUMAN RIGHTS COMMISSION,1,Legal Affairs,62397.0,71757.0,False,"(-250.0, 83333.333]"

In [66]:
df = pd.DataFrame({'A':[1,2,3], 'B':[400,500,600]})
new_df = pd.DataFrame({'B':[4,5,6], 'C':[7,8,9]})

In [67]:
df

   A    B
0  1  400
1  2  500
2  3  600

In [68]:
new_df

   B  C
0  4  7
1  5  8
2  6  9

In [70]:
df.update(new_df)
df

   A  B
0  1  4
1  2  5
2  3  6